CC = g++
FLAGS = -std=c++11 -Wall -Werror -Wno-sign-compare -Wno-unused-result
CPP = main.cpp TBinaryTree.cpp TBinaryTreeItem.cpp Rhomb.cpp Pentagon.cpp Hexagon.cpp
NAME = main

all:
	$(CC) $(FLAGS) -o $(NAME) $(CPP)


